# Generated by Django 4.1.3 on 2023-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogfile_options_post_category_tag_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted on'),
        ),
        migrations.AlterField(
            model_name='blogfile',
            name='is_deleted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='blogfile',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blogfile',
            name='url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted on'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='is_deleted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted on'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=256, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='عنوان'),
        ),
    ]
